// Optional browser acceptance test. Set PLAYWRIGHT_MODULE to an installed module path.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname,'../docs');
const snapshot=JSON.parse(fs.readFileSync(path.join(root,'data/delivery.json'),'utf8'));
const companySnapshot=JSON.parse(fs.readFileSync(path.join(root,'data/ecosystem.json'),'utf8'));
const evidence = path.resolve(__dirname,'../.local/browser');
fs.mkdirSync(evidence,{recursive:true});
const mime={'.html':'text/html','.css':'text/css','.js':'application/javascript','.svg':'image/svg+xml','.json':'application/json','.xml':'application/xml'};
const server=http.createServer((req,res)=>{
 const pathname=new URL(req.url,'http://localhost').pathname;
 if(!pathname.startsWith('/stack_ledger/')){res.writeHead(404);res.end();return;}
 let filename=path.resolve(root,decodeURIComponent(pathname.slice('/stack_ledger/'.length)) || '.');
 if(filename!==root && !filename.startsWith(root+path.sep)){res.writeHead(403);res.end();return;}
 if(fs.existsSync(filename)&&fs.statSync(filename).isDirectory())filename=path.join(filename,'index.html');
 if(!fs.existsSync(filename)){res.writeHead(404);res.end();return;}
 res.setHeader('Content-Type',mime[path.extname(filename)]||'text/plain');fs.createReadStream(filename).pipe(res);
});
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const origin=`http://127.0.0.1:${server.address().port}/stack_ledger/`;
 const browser=await chromium.launch({channel:'chrome',headless:true});
 try{
  // The public homepage contract must survive disabled JavaScript and failed fetches.
  const staticContext=await browser.newContext({javaScriptEnabled:false,viewport:{width:1440,height:1000}});
  const staticPage=await staticContext.newPage();await staticPage.goto(origin);
  assert.match(await staticPage.locator('h1').innerText(),/A public record of\s+the AI buildout/);
  assert.equal(await staticPage.locator('.layer-card').count(),5);
  assert.equal(await staticPage.locator('.headline-source').count(),5);
  assert.match(await staticPage.locator('[data-layer="chips"]').innerText(),/CoWoS/);
  assert.match(await staticPage.locator('[data-layer="infrastructure"]').innerText(),/Abilene/);
  assert.match(await staticPage.locator('[data-layer="models"]').innerText(),/1\.75[\s\S]*Sep 7, 2026[\s\S]*GPT-5\.3-Codex/);
  assert.match(await staticPage.locator('[data-layer="applications"]').innerText(),/500,000[\s\S]*Mar 2026/);
  assert.match(await staticPage.locator('[data-layer="applications"]').innerText(),/paid trips/);
  assert.match(await staticPage.locator('#runtime').innerText(),/RTX 5090.*Last run:.*Last successful research:/s);
  assert.ok(await staticPage.locator('noscript a[href$="data/ledger.json"]').isVisible());
  await staticPage.locator('.stack-menu summary').focus();await staticPage.keyboard.press('Enter');
  assert.equal(await staticPage.locator('.stack-destinations a:visible').count(),5);
  await staticPage.keyboard.press('Tab');await staticPage.keyboard.press('Enter');
  await staticPage.waitForURL('**/energy/');
  await staticPage.goto(origin);await staticPage.locator('.slab').first().focus();await staticPage.keyboard.press('Enter');
  await staticPage.waitForURL('**/energy/');
  await staticContext.close();
  const fallback=await browser.newPage();await fallback.route('**/data/*.json',route=>route.abort());
  await fallback.goto(origin);await fallback.locator('#load-status').waitFor();
  assert.equal(await fallback.locator('.layer-card').count(),5);
  assert.match(await fallback.locator('h1').innerText(),/A public record/);await fallback.close();
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const routes=['','energy/','chips/','infrastructure/','models/','applications/','companies/','industry/','projects/','ledger/','methodology/'];
  routes.push(...['nvidia','tsmc','asml','openai','openclaw','nebius','innolight','aws'].map(id=>`companies/${id}/`));
  for(const route of routes){
   const response=await page.goto(origin+route,{waitUntil:'networkidle'});assert.equal(response.status(),200);
   await page.locator('body[data-enhanced="true"]').waitFor();
   assert.equal(await page.locator('h1').count(),1);
   assert.deepEqual(await page.locator('[id]').evaluateAll(els=>{const ids=els.map(el=>el.id);return ids.filter((id,i)=>ids.indexOf(id)!==i);}),[],route+' duplicate IDs');
   assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,route+' desktop overflow');
   const links=await page.locator('a[href]').evaluateAll(as=>as.map(a=>new URL(a.getAttribute('href'),location.href).href).filter(u=>u.startsWith(location.origin)&&!u.includes('#')));
   for(const href of new Set(links)){assert.equal((await page.request.get(href)).status(),200,href);}
  }
  await page.goto(origin+'projects/');await page.locator('#project-count').waitFor();
  const signedChart=await page.evaluate(()=>{
   const observation=data.observations.find(o=>o.metric==='us-generation-growth-h1'),original=observation.value;
   try{observation.value=-37;const box=document.createElement('div');box.innerHTML=chart(observation.metric);const bar=box.querySelector('.bar rect');return {y:Number(bar.getAttribute('y')),height:Number(bar.getAttribute('height')),zero:Number(box.querySelector('.zero-baseline').getAttribute('d').match(/M\S+ ([\d.]+)/)[1]),text:box.textContent};}
   finally{observation.value=original;}
  });
  assert.equal(signedChart.y,signedChart.zero);assert.ok(signedChart.height>0&&signedChart.y+signedChart.height<=227);assert.match(signedChart.text,/-37/);
  assert.equal(await page.locator('.delivery-card').count(),snapshot.projects.length);
  await page.locator('[data-project-layer="energy"]').click();assert.equal(await page.locator('.delivery-card').count(),snapshot.projects.filter(p=>p.layer==='energy').length);
  await page.selectOption('#project-stage','operating');assert.equal(await page.locator('.delivery-card').count(),2);
  await page.locator('#project-search').fill('Quebec');assert.equal(await page.locator('.delivery-card').count(),1);
  await page.locator('.delivery-history summary').click();assert.match(await page.locator('.delivery-history').innerText(),/1,250|transmission/i);
  await page.locator('#project-search').fill('missing-project');assert.equal(await page.locator('.delivery-card').count(),0);
  await page.locator('#project-search').fill('');await page.selectOption('#project-stage','all');await page.locator('[data-project-layer="infrastructure"]').click();
  assert.match(await page.locator('#project-fairwater-one .observed').innerText(),/369/);
  assert.match(await page.locator('#project-fairwater-two .unknown').innerText(),/Not quantified/);
  assert.equal(await page.locator('#project-abilene .planned').count(),1);
  await page.locator('[data-project-layer="all"]').click();
  assert.match(await page.locator('#project-tesla-robotaxi .delivery-quantities').innerText(),/1,000,000[\s\S]*unsupervised miles[\s\S]*Sep 3, 2026/);
  assert.match(await page.locator('#project-tesla-fsd .delivery-owner').innerText(),/Netherlands/);
  assert.match(await page.locator('#project-tesla-optimus .stage').innerText(),/Pilot/);
  assert.equal(await page.locator('#project-colossus-two .project-measures').first().getAttribute('open'),'');
  await page.screenshot({path:path.join(evidence,'projects.png'),fullPage:true});
  await page.goto(origin+'companies/?layer=chips');await page.locator('#company-count').waitFor();
  assert.equal(await page.locator('[data-company-filter="chips"]').getAttribute('aria-pressed'),'true');
  assert.ok(await page.locator('.company-card').count()>=10);
  await page.locator('#company-search').fill('lithography');
  assert.equal(await page.locator('.company-card').count(),1);
  assert.match(await page.locator('.company-card').innerText(),/ASML/);
  await page.locator('#company-search').fill('');await page.locator('[data-company-filter="all"]').click();
  await page.selectOption('#revenue-basis','run-rate');assert.equal(await page.locator('.company-card').count(),2);
  assert.equal(await page.locator('.company-revenue.run-rate').count(),2);
  await page.selectOption('#revenue-basis','annual');assert.equal(await page.locator('.company-card').count(),companySnapshot.companies.filter(c=>c.revenue_kind==='annual').length);
  await page.selectOption('#revenue-basis','unavailable');assert.equal(await page.locator('.company-card').count(),companySnapshot.companies.filter(c=>c.revenue_kind==='unavailable').length);
  assert.equal(await page.locator('.company-revenue.unavailable').count(),companySnapshot.companies.filter(c=>c.revenue_kind==='unavailable').length);
  assert.match(await page.locator('#lightmatter').innerText(),/Not yet verified/);
  await page.selectOption('#revenue-basis','all');await page.screenshot({path:path.join(evidence,'companies.png'),fullPage:true});
  await page.goto(origin+'infrastructure/');await page.locator('#fabric-count').waitFor();
  assert.equal(await page.locator('.component-card').count(),10);
  await page.locator('#fabric-search').fill('DSP');assert.ok(await page.locator('.component-card').count()>0);
  assert.ok(await page.locator('#component-signal a[href$="companies/marvell/"]').count());
  await page.locator('#fabric-search').fill('nonexistent-component');assert.equal(await page.locator('.component-card').count(),0);
  await page.locator('.fabric-path a').first().click();assert.equal(await page.locator('.component-card').count(),10);
  await page.evaluate(()=>{document.activeElement.blur();window.scrollTo({top:0,behavior:'instant'});});
  await page.screenshot({path:path.join(evidence,'infrastructure.png'),fullPage:true});
  await page.goto(origin+'models/');await page.locator('#agent-products').waitFor();
  assert.equal(await page.locator('#agent-harnesses table tbody tr').count(),4);
  assert.equal(await page.locator('#frontier-models table tbody tr').count(),5);
  assert.equal(await page.locator('#premium-model-plans table tbody tr').count(),7);
  assert.match(await page.locator('#frontier-astra6').innerText(),/1,050,000/);
  assert.match(await page.locator('#frontier-grok47').innerText(),/release not verified/);
  assert.match(await page.locator('#premium-supergrok-heavy').innerText(),/current price unverified/);
  assert.match(await page.locator('#frontier-grok-bot').innerText(),/not a new base model/);
  await page.locator('#frontier-models').screenshot({path:path.join(evidence,'frontier-models.png')});
  assert.match(await page.locator('#codex-cloud').innerText(),/Hosted execution/);
  assert.match(await page.locator('#open-weight-licenses').innerText(),/Apache 2.0/);
  assert.equal(await page.locator('.agent-card').count(),9);
  assert.match(await page.locator('#agent-codex').innerText(),/1.75/);
  await page.goto(origin+'applications/');await page.locator('#named-projects').waitFor();
  assert.match(await page.locator('#medicine-intismeran').innerText(),/1,137/);
  assert.match(await page.locator('#medicine-intismeran').innerText(),/not an approval/);
  assert.match(await page.locator('#science-weather').innerText(),/operational support/);
  assert.match(await page.locator('#named-projects').innerText(),/supervis|Supervis/);
  await page.goto(origin+'industry/');await page.locator('.industry-verdict').waitFor();
  assert.equal(await page.locator('#construction-economy .chart-wrap').count(),2);
  assert.match(await page.locator('#gc-mortenson').innerText(),/outside-plant fiber/);
  assert.equal(await page.locator('.jobs-comparison tbody tr').count(),5);
  assert.match(await page.locator('.jobs-comparison').innerText(),/Terafab[\s\S]*Hyperion/);
  assert.equal(await page.locator('#projects .project-card').count(),snapshot.projects.filter(p=>p.layer==='chips').length);
  assert.equal(await page.locator('.jobs-comparison tbody tr:first-child td:last-child').innerText(),'Not verified');
  assert.match(await page.locator('#capital-evidence').innerText(),/contracts awarded|Contracts awarded/);
  assert.match(await page.locator('#electrical-work').innerText(),/72,700/);
  assert.equal(await page.locator('.energy-case').count(),3);
  assert.equal(await page.locator('.energy-case').first().locator('.planned').count(),0);
  assert.equal(await page.locator('.energy-case').last().locator('.planned').count(),2);
  assert.equal(await page.locator('.project-card .operating').count(),1);
  assert.equal(await page.locator('.supply-step').count(),5);
  assert.equal(await page.locator('.capacity-grid .chart-wrap').count(),4);
  assert.match(await page.locator('.employment-chart').innerText(),/-23,000/);
  assert.equal(await page.locator('#trades-long-view .definition-break-marker').count(),1);
  assert.match(await page.locator('#trades-long-view .methodology-break').innerText(),/2021/);
  await page.screenshot({path:path.join(evidence,'industry.png'),fullPage:true});
  await page.goto(origin);await page.locator('.layer-card').first().waitFor();
  assert.equal(await page.locator('#historical-context [data-metric="us-utility-generation-history"] .bar').count(),12);
  assert.equal(await page.locator('#historical-context [data-metric="us-utility-generation-history"] .bar rect[fill^="url"]').count(),5);
  assert.equal(await page.locator('#historical-context .scope-break-marker').count(),1);
  assert.match(await page.locator('#historical-context .scope-warning').innerText(),/2028.*broader.*Counterfactual Baseline/);
  assert.equal(await page.locator('#historical-context [data-metric="revenue-tsmc"] .bar').count(),7);
  assert.equal(await page.locator('#historical-context [data-metric="revenue-nvidia"]').count(),0);
  assert.equal(await page.locator('#historical-context [data-metric="revenue-asml"]').count(),0);
  await page.locator('#historical-context').screenshot({path:path.join(evidence,'history-context.png')});
  assert.equal(await page.locator('#application-outcomes [data-metric="waymo-paid-weekly"] .bar').count(),2);
  assert.equal(await page.locator('#application-outcomes [data-metric="digit-gxo-totes"] .bar').count(),1);
  assert.match(await page.locator('#application-outcomes').innerText(),/sourced operating results[\s\S]*not a productivity total/i);
  await page.locator('#application-outcomes').screenshot({path:path.join(evidence,'application-outcomes.png')});
  assert.equal(await page.locator('.stack-svg a.slab').count(),5);
  assert.equal(await page.locator('#outlook .target-mini').count(),JSON.parse(fs.readFileSync(path.join(root,'data/ledger.json'),'utf8')).targets.length);
  assert.ok(await page.evaluate(()=>document.querySelector('#stack').compareDocumentPosition(document.querySelector('#premise'))&Node.DOCUMENT_POSITION_FOLLOWING));
  await page.locator('.stack-menu summary').click();await page.keyboard.press('Escape');
  assert.equal(await page.locator('.stack-menu').getAttribute('open'),null);
  await page.locator('.stack-svg a[aria-label="Explore layer 01: Energy"]').click();
  await page.waitForURL('**/energy/');await page.locator('#metric-select').waitFor();
  assert.equal(await page.locator('#colossus-power-path .power-path>li').count(),5);
  assert.match(await page.locator('#colossus-power-path').innerText(),/Southaven[\s\S]*separate Colossus 2/i);
  await page.selectOption('#metric-select','us-dc-electricity');
  assert.match(await page.locator('#metric-chart').innerText(),/325–580/);
  await page.locator('#metric-chart summary').click();assert.equal(await page.locator('#metric-chart tbody tr').count(),2);
  await page.locator('#metric-chart .history-window').check();assert.equal(await page.locator('#metric-chart tbody tr').count(),3);
  await page.selectOption('#metric-select','us-utility-generation-history');
  assert.equal(await page.locator('#metric-chart .bar').count(),12);
  await page.locator('#metric-chart .history-window').check();assert.equal(await page.locator('#metric-chart .bar').count(),17);
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.locator('#metric-chart .bar').count(),17);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.setViewportSize({width:1440,height:1000});
  await page.selectOption('#metric-select','dc-electricity-iea2025-high-efficiency');
  assert.match(await page.locator('#metric-chart .chart-history').innerText(),/2035 forecast/);
  assert.equal(await page.locator('#metric-chart .bar rect[fill^="url"]').count(),1);
  await page.evaluate(()=>{data.observations.push({...data.observations.find(o=>o.metric==='dc-electricity-iea2025-high-efficiency'&&o.status==='forecast'),id:'browser-only-future',year:2040,period:'2040'});document.querySelector('#metric-chart').innerHTML=chart('dc-electricity-iea2025-high-efficiency');});
  assert.match(await page.locator('#metric-chart .chart-history').innerText(),/Window: 2024–2040/);
  await page.selectOption('#metric-select','us-nuclear');assert.match(await page.locator('#metric-chart').innerText(),/2050/);
  await page.goto(origin+'ledger/?layer=chips');await page.locator('#research-search').waitFor();
  assert.equal(await page.locator('[data-layer="chips"]').getAttribute('aria-pressed'),'true');
  await page.locator('#research-search').fill('zz-no-such-record');assert.match(await page.locator('#result-count').innerText(),/0 research notes and 0 observations/);
  await page.locator('#research-search').fill('');await page.locator('[data-layer="all"]').click();
  const downloaded=page.waitForEvent('download');await page.locator('#download-csv').click();const csv=await downloaded;await csv.saveAs(path.join(evidence,'observations.csv'));
  assert.match(fs.readFileSync(path.join(evidence,'observations.csv'),'utf-8'),/source_url/);
  await page.goto(origin);await page.locator('.hero').waitFor();await page.screenshot({path:path.join(evidence,'desktop.png'),fullPage:true});await page.screenshot({path:path.join(evidence,'homepage-viewport.png')});
  for(const width of [390,768]){
   await page.setViewportSize({width,height:844});
   for(const route of routes){await page.goto(origin+route);await page.locator('body[data-enhanced="true"]').waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,route+' overflow at '+width);}
  }
  await page.setViewportSize({width:390,height:844});await page.goto(origin);await page.locator('.hero').waitFor();await page.screenshot({path:path.join(evidence,'mobile.png'),fullPage:true});
  await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.className),'skip');
  assert.deepEqual(errors,[]);
  await page.goto(origin+'companies/asml/');await page.locator('body[data-enhanced="true"]').waitFor();
  assert.match(await page.locator('#revenue').innerText(),/2030/);
  assert.equal(await page.locator('#revenue .bar rect[fill^="url"]').count(),3);
  assert.doesNotMatch(await page.locator('#revenue').innerText(),/Broader AEO/);
  await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:path.join(evidence,'company-asml.png'),fullPage:true});
  await page.goto(origin+'companies/tsmc/');await page.locator('body[data-enhanced="true"]').waitFor();
  assert.match(await page.locator('#revenue').innerText(),/TWD billion/);
  assert.equal(await page.locator('[data-metric="revenue-tsmc"] .bar').count(),7);
  assert.deepEqual(errors,[]);
  console.log(`Browser acceptance passed: ${routes.length} routes, 3 viewports, company revenue histories/forecasts, filters, navigation, keyboard access and no page errors.`);
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
