"""Render the reviewed claims snapshot without requiring JavaScript or network data."""
from html import escape as e


def water_values(w):
    """US liquid gallon and international avoirdupois pound; no rounded intermediates."""
    almond_liters=w['blue_gallons_per_pound']*w['almond_grams']/453.59237*3.785411784
    query_ml=w['query_gallons']*3785.411784
    return almond_liters,query_ml,almond_liters*1000/query_ml


def water_feature(w, citations):
    liters,ml,ratio=water_values(w)
    return f'''<section class="section" id="water-perspective"><div class="eyebrow">WATER IN PERSPECTIVE / A CONDITIONAL CALCULATION</div><h2>One almond. An explicit comparison.</h2><p class="section-intro">Using a historical irrigation estimate, an assumed {w['almond_grams']:g}-gram kernel and Sam Altman’s reported ChatGPT average, the arithmetic gives <strong>about {round(ratio/1000)*1000:,} queries per almond</strong>. This is a conditional volume comparison, not a verified equivalence of water footprints.</p><div class="water-equation"><div><span>Estimated irrigation consumption</span><strong>{liters:.1f} L</strong><p>Per assumed {w['almond_grams']:g} g almond<br>{e(w['almond_period'])}</p></div><span class="water-operator" aria-hidden="true">÷</span><div><span>Altman-reported query average</span><strong>{ml:.2f} mL</strong><p>Per query<br>{e(w['query_period'])}</p></div><span class="water-operator" aria-hidden="true">≈</span><div><span>Calculated ratio, rounded</span><strong>{round(ratio/1000)*1000:,}</strong><p>Queries per assumed almond<br>Conditional on the reported query figure</p></div></div><p><strong>The almond side uses blue water only:</strong> irrigation water consumed. Rainfall (green water) and the pollution-assimilation indicator (grey water) are excluded. The report is hosted by the Almond Board and concerns historical California production, not today’s worldwide average.</p><p><strong>The unresolved part is the query measurement:</strong> Altman’s post does not disclose sufficient model, task, location, period or water-accounting methodology to verify a like-for-like comparison. The number does not establish how much water your prompt uses or whether a particular watershed can support a campus.</p><details class="water-method"><summary>See the calculation and assumptions</summary><p>{w['blue_gallons_per_pound']:g} US gallons of blue water per pound of kernels × {w['almond_grams']:g} g ÷ 453.59237 g per pound = {liters:.3f} liters per assumed kernel.</p><p>{w['query_gallons']:g} US gallons per reported average query × 3,785.411784 mL per US gallon = {ml:.6f} mL.</p><p>Divide the unrounded almond volume by the unrounded query volume: {ratio:,.0f}. The display rounds to the nearest thousand. The kernel mass is an illustrative assumption, not a measured average from this report. A larger kernel increases the ratio proportionally; a more water-intensive query reduces it.</p><p>These are different products with different benefits. A volume comparison does not rank their social value or imply that water conserved in one location is available in another.</p></details>{citations(w['sources'])}<p><a class="source-inline" href="#water-national-context">See national data-center and golf context ↓</a></p></section>'''

def render_claims(data, sources, base='../'):
    sources = {s['id']: s for s in sources}

    def citations(ids):
        return '<ul class="claim-sources">' + ''.join(
            f'<li><a href="{e(sources[s]["url"], quote=True)}">{e(sources[s]["publisher"])} · {e(sources[s]["title"])} ↗</a>'
            f'<span>Published {e(sources[s]["published"] or "date not disclosed")} · reviewed {e(data["reviewed_at"][:10])}</span></li>' for s in ids) + '</ul>'

    topics = list(dict.fromkeys(c['topic'] for c in data['claims']))
    graphics = ''
    for g in data['highlights']:
        maximum = max(p['value'] for p in g['points']) * 1.12
        bars = ''.join(f'<div class="evidence-bar-row"><div><span>{e(p["period"])}</span><strong>{p["value"]:g}</strong></div>'
                       f'<div class="evidence-bar-track"><span class="evidence-bar {p["status"]}" style="width:{p["value"]/maximum*100:.3f}%"></span></div>'
                       f'<small>{e(p["status"].capitalize())}</small></div>' for p in g['points'])
        rows = ''.join(f'<tr><th scope="row">{e(p["period"])}</th><td>{p["value"]:g}</td><td>{e(p["status"])}</td></tr>' for p in g['points'])
        graphics += f'<figure class="evidence-graphic"><div class="eyebrow">BENEFITS IN VIEW</div><h3>{e(g["title"])}</h3><p>{e(g["scope"])}</p><p class="evidence-unit">{e(g["unit"])}</p><div aria-hidden="true">{bars}</div><details><summary>Data & scope</summary><table><caption>{e(g["title"])} · {e(g["unit"])}</caption><thead><tr><th>Period</th><th>Value</th><th>Status</th></tr></thead><tbody>{rows}</tbody></table></details><figcaption>{e(g["note"])}</figcaption>{citations([g["source"]])}</figure>'
    cards = ''
    for c in data['claims']:
        cards += f'<article class="claim-card" id="{e(c["id"])}" data-topic="{e(c["topic"], quote=True)}"><div class="claim-meta"><span>{e(c["topic"])}</span><a href="#{e(c["id"])}" aria-label="Link to this claim">#</a></div><h3>{e(c["claim"])}</h3><p class="claim-verdict">{e(c["verdict"])}</p><p class="claim-scope">{e(c["scope"])}</p><h4>What the evidence says</h4><p>{e(c["evidence"])}</p><div class="claim-future"><h4>What future projects should show</h4><p>{e(c["future"])}</p></div><details><summary>Limits & sources</summary><p>{e(c["gap"])}</p>{citations(c["sources"])}</details></article>'
    audits = ''.join(f'<article class="article-check"><div><h3>{e(a["claim"])}</h3><span class="claim-verdict">{e(a["status"])}</span></div><p>{e(a["finding"])}</p>{citations(a["sources"])}</article>' for a in data['article_audit'])
    options = ''.join(f'<option>{e(t)}</option>' for t in topics)
    return f'''<section class="page-hero claims-hero"><div class="eyebrow">CLAIMS & EVIDENCE / THE PUBLIC BENEFIT</div><h1>Build more.<br>Know what it delivers.</h1><p>The opportunity is substantial: skilled work, local revenue, more power and useful intelligence. Examine the evidence behind both the benefits and the concerns.</p><div class="claims-jump"><a href="#evidence-review">Explore {len(data['claims'])} claims ↓</a><a href="#water-perspective">Water in perspective</a><a href="#article-review">The linked article, checked ↓</a><a href="{base}projects/">Follow the projects ↗</a></div><p class="claim-scope">Reviewed {e(data['reviewed_at'][:10])} · {e(data['reviewer'])}</p></section>
    <section class="section evidence-highlights" aria-label="Sourced indicators of economic benefit">{graphics}</section>
    {water_feature(data['water_comparison'], citations)}
    <aside class="reading-note"><strong>A growing evidence file, not a final verdict on every project.</strong><p>This review covers recurring public claims and the material quantitative arguments in the linked article. Local findings stay local; estimates, forecasts and reported outcomes stay distinct. “Not established” means the evidence reviewed does not settle the claim. Future-project criteria are Stack Ledger’s research recommendations.</p></aside>
    <section class="section" id="evidence-review"><div class="section-top"><div><div class="eyebrow">POWER → FACTORIES → USEFUL WORK</div><h2>The claims, examined.</h2></div></div><form class="claims-controls" hidden role="search"><label>Topic<select id="claim-topic"><option value="">All topics</option>{options}</select></label><label>Search claims<input id="claim-search" type="search" placeholder="Try water, wages or taxes"></label><button type="reset">Clear filters</button></form><p id="claims-count" role="status" aria-live="polite">{len(data['claims'])} claims</p><div class="claims-grid">{cards}</div><p id="claims-empty" hidden>No matching claims. Try another topic or search term.</p></section>
    <section class="section" id="article-review"><div class="eyebrow">SOURCE AUDIT / SEPTEMBER 2026</div><h2>What the jobs article establishes.</h2><p class="section-intro">The BizNews article republishes The Economist. Some headline figures match primary releases; other estimates need underlying datasets and methods. Unresolved items remain visible and are excluded from benefit charts.</p>{citations(['claims-biznews'])}<div class="article-checks">{audits}</div></section>
    <section class="manifesto"><div><h2>Turn the opportunity into receipts.</h2><p>Follow projects from announcement to operation, then measure local hires, paid contracts, tax collections, delivered power and completed work. These outcomes will determine how much reindustrialization reaches the community.</p></div><a href="{base}projects/">Track delivery ↗</a></section><p class="reading-note"><a href="{base}data/claims.json">Download this reviewed evidence file</a> · <a href="https://github.com/reedos/stack_ledger/issues">Submit a claim or correction ↗</a></p>'''
